#!/usr/bin/env bash

print_style () {
    if [ "$2" == "info" ] ; then
        COLOR="96m"
    elif [ "$2" == "success" ] ; then
        COLOR="92m"
    elif [ "$2" == "warning" ] ; then
        COLOR="93m"
    elif [ "$2" == "danger" ] ; then
        COLOR="91m"
    else #default color
        COLOR="0m"
    fi

    STARTCOLOR="\e[$COLOR"
    ENDCOLOR="\e[0m"

    printf "$STARTCOLOR%b$ENDCOLOR" "$1"
}

display_options () {
    printf "Available options:\n";
    print_style "   ga" "info"; printf "\t Enter workspace with laradock user and moved to api\n"
}

# Exec to workspace
go_to () {
    cc="${dcm} ${ctn} bash"
    print_style "Run: ${cc}\n" "info"
    ${cc}
}

# Step install app 
set_up () {
    command "composer install"
    command "php artisan migrate --seed"
}

command () {
    cc="${dcm} ${ctn} $1"
    print_style "Run: ${cc}\n" "info"
    ${cc}
}

cws="/var/www"
ctn="research_workspace_1"
dcm="docker exec -it -u laradock"
nit="docker exec -u laradock"

case $1 in
    ga)
        go_to
        ;;
    setup)
        set_up
        ;;
    *)
        display_options
        ;;
esac